version: "3.4"
services:
  adminer:
    image: adminer
    container_name: lamp-server-adminer
    restart: always    
    links: 
      - postgresql
      - mysql
    networks:
      - backend
    ports:
      - 8080:8080
  php72:
    build: './php72/'
    container_name: lamp-server-php72
    depends_on:
      - postgresql
      - mysql    
    restart: always
    networks:
      - backend
    environment:
      APACHE_RUN_USER: '#1000'
    sysctls:
      net.ipv4.ip_unprivileged_port_start: '0'    
    volumes:
      - /var/www/html/:/var/www/html/
    ports:      
      - "8072:80"
  php56:
    build: './php56/'
    container_name: lamp-server-php56
    depends_on:
      - postgresql
      - mysql    
    restart: always
    networks:
      - backend    
    volumes:
      - /var/www/html/:/var/www/html/
    ports:      
      - "8056:80"      
  mysql:
    image: mysql:5.6.42
    container_name: lamp-server-mysql
    restart: always    
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  postgresql:
    image: postgres:10.6
    container_name: lamp-server-postgresql
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres    
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data      
networks:
  backend:
volumes:
  mysql-data:
      name: mysql-data 
  postgres-data:
      name: postgres-data       
