version: "3.4"
services:
  php70:
    build: './php70/'
    container_name: lamp-server-php70
    depends_on:
      - postgresql
      - mysql    
    restart: always
    networks:
      - backend    
    volumes:
      - c:/Bitnami/wampstack-5.6.34-0/apache2/htdocs/:/var/www/html/
    ports:      
      - "8070:80"
  php56:
    build: './php56/'
    container_name: lamp-server-php56
    depends_on:
      - postgresql
      - mysql    
    restart: always
    networks:
      - backend    
    volumes:
      - c:/Bitnami/wampstack-5.6.34-0/apache2/htdocs/:/var/www/html/
    ports:      
      - "8056:80"      
  mysql:
    image: mysql:5.6.42
    container_name: lamp-server-mysql
    restart: always    
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  postgresql:
    image: postgres:10.6
    container_name: lamp-server-postgresql
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres    
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data      
networks:
  backend:
volumes:
  mysql-data:
      name: mysql-data 
  postgres-data:
      name: postgres-data       